### GET root test
GET http://localhost:3000/

### POST create task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Learn",
  "description": "Node"
}

### GET all tasks
GET http://localhost:3000/tasks

### GET one task
GET http://localhost:3000/tasks/{id}

### PATCH update task
PATCH http://localhost:3000/tasks/{id}
Content-Type: application/json

{
  "status" : "completed"
}

### DELETE task remove
DELETE http://localhost:3000/tasks/{id}


### POST add new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "marija@example.com",
  "password": "123",
  "name": "Marija"
}

### POST Registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "test7@example.com",
  "password": "12345",
  "name": "Test User"
}

### POST Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test4@example.com",
  "password": "12345"
}